version: "3.4"

services:

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "events"
      MYSQL_USER: "agent"
      MYSQL_PASSWORD: "secret"
    volumes:
      - ./scripts/create-events-table.sql:/docker-entrypoint-initdb.d/01-init.sql
    tmpfs:
      - /var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0
    ports:
      - "80:80"
    environment:
      PMA_HOSTS: "mysql"
      PMA_USER: "agent"
      PMA_PASSWORD: "secret"